<?php

namespace App\Exports;

use Maatwebsite\Excel\Concerns\FromCollection;
use Maatwebsite\Excel\Concerns\WithHeadings;
use Maatwebsite\Excel\Concerns\WithMapping;
use Maatwebsite\Excel\Concerns\WithStyles;
use PhpOffice\PhpSpreadsheet\Worksheet\Worksheet;
use App\Models\{Pump, Fan, Compressor, Motor, Chiller, Boiler, Cooling, Ahu, Information};

class EquipmentExport implements FromCollection, WithHeadings, WithMapping, WithStyles
{
    protected $itemType;
    protected $projectId;

    public function __construct($itemType, $projectId)
    {
        $this->itemType = strtolower($itemType);
        $this->projectId = $projectId;
    }

    public function collection()
    {
        switch ($this->itemType) {
            case 'pump':
                return Pump::whereHas('information', function ($q) {
                    $q->where('project_id', $this->projectId);
                })->with('information')->get();

            case 'fan':
                return Fan::whereHas('information', function ($q) {
                    $q->where('project_id', $this->projectId);
                })->with('information')->get();

            case 'compressor':
                return Compressor::whereHas('information', function ($q) {
                    $q->where('project_id', $this->projectId);
                })->with('information')->get();

            case 'chiller':
                return Chiller::whereHas('information', function ($q) {
                    $q->where('project_id', $this->projectId);
                })->with('information')->get();

            case 'motor':
                return Motor::whereHas('information', function ($q) {
                    $q->where('project_id', $this->projectId);
                })->with('information')->get();

            case 'boiler':
                return Boiler::whereHas('information', function ($q) {
                    $q->where('project_id', $this->projectId);
                })->with('information')->get();

            case 'cooling':
                return Cooling::whereHas('information', function ($q) {
                    $q->where('project_id', $this->projectId);
                })->with('information')->get();

            case 'ahu':
                return Ahu::whereHas('information', function ($q) {
                    $q->where('project_id', $this->projectId);
                })->with('information')->get();

            default:
                return collect();
        }
    }

    public function headings(): array
    {
        switch ($this->itemType) {
            case 'pump':
                return [
                    'Project Name',
                    'Equipment',
                    'Location',
                    'Make & Model',
                    'Year Of Installation',
                    'Flow Rated',
                    'Flow Measured',
                    'UOM',
                    'Head Rated',
                    'Head Measured',
                    'UOM',
                    'Voltage Rated',
                    'Voltage Measured',
                    'UOM',
                    'Current Rated',
                    'Current Measured',
                    'UOM',
                    'Power Factor Rated',
                    'Power Factor Measured',
                    'Motor Power Rated',
                    'Motor Power Measured',
                    'UOM',
                    'Frequency Rated',
                    'Frequency Measured',
                    'UOM',
                    'Speed Rated',
                    'Speed Measured',
                    'UOM',
                    'Motor Efficiency Rated',
                    'UOM',
                    'Motor Efficiency Class Rated',
                    'Motor Frame Size Rated',
                    'Insulation Class Rated',
                    'Suction Head Measured',
                    'UOM',
                    'Discharge Head Measured',
                    'UOM',
                    'Pump Efficiency Rated',
                    'Pump Efficiency Measured',
                    '',
                    'VFD or Not',
                    'VFD setting in Hz',
                    'Pump throttling',
                    'Flow Modulation required',
                    'Parallel pump operation',
                    'Nos. of rewinding of motor',
                    'Check cavitation',
                    'Operating Hours in day',
                    'Observations',
                ];

            case 'fan':
                return [
                    'Project Name',
                    'Equipment',
                    'Location',
                    'Make & Model',
                    'Year Of Installation',
                    'Flow Rated',
                    'Flow Measured',
                    'UOM',
                    'Head Rated',
                    'UOM',
                    'Voltage Rated',
                    'Voltage Measured',
                    'UOM',
                    'Current Rated',
                    'Current Measured',
                    'UOM',
                    'Power Factor Rated',
                    'Power Factor Measured',
                    'Motor Power Rated',
                    'Motor Power Measured',
                    'UOM',
                    'Frequency Rated',
                    'Frequency Measured',
                    'UOM',
                    'Speed Rated',
                    'Speed Measured',
                    'UOM',
                    'Motor Efficiency Rated',
                    'UOM',
                    'Motor Efficiency Class Rated',
                    'Motor Frame Size Rated',
                    'Insulation Class Rated',
                    'Suction Duct Size Measured',
                    'UOM',
                    'Suction Static Pressure Measured',
                    'Suction Static Pressure Average',
                    'UOM',
                    'Suction Velocity pressure Measured',
                    'Suction Velocity pressure Average',
                    'UOM',
                    'Discharge Duct Size Measured',
                    'UOM',
                    'Discharge Static pressure Measured',
                    'Discharge Static pressure Average',
                    'UOM',
                    'Discharge Velocity Pressure Measured',
                    'Discharge Velocity Pressure Average',
                    'UOM',
                    'Discharge Velocity Measured',
                    'Discharge Velocity Average',
                    'UOM',
                    'Fan Efficiency Rated',
                    '',
                    'VFD or Not',
                    'VFD setting',
                    'Damper opening %',
                    'Flow Modulation Required',
                    'Parallel fan operation',
                    'Nos. of rewinding of motor',
                    'Operating Hours',
                    'Observations',
                ];

            case 'compressor':
                return [
                    'Project Name',
                    'Equipment',
                    'Location',
                    'Make & Model',
                    'Year Of Installation',
                    'Flow Rated',
                    'Flow Measured
                    UOM',
                    'Pressure Rated',
                    'Pressure Measured',
                    'UOM',
                    'Voltage Rated',
                    'Voltage Measured',
                    'UOM',
                    'Current Rated',
                    'Current Measured',
                    'UOM',
                    'Power Factor Rated',
                    'Power Factor Measured',
                    'Motor Power Rated',
                    'Motor Power Measured',
                    'UOM',
                    'Frequency Rated',
                    'Frequency Measured',
                    'UOM',
                    'Speed Rated',
                    'Speed Measured',
                    'UOM',
                    'Motor Efficiency Rated',
                    'UOM',
                    'Motor Efficiency Class Rated',
                    'Motor Frame Size Rated',
                    'Insulation Class Rated',
                    'Load Pressure Measured',
                    'UOM',
                    'Unload Pressure Measured',
                    'UOM',
                    'Receiver Size Measured',
                    'UOM',
                    'Pipe Volume Measured',
                    'UOM',
                    'Initial Pressure Measured',
                    'UOM',
                    'Initial Pressure Measured',
                    'UOM',
                    'Time to reach final pressure Measured',
                    'UOM',
                    'Temperature Measured',
                    'UOM',
                    'Compressor SEC Rated',
                    'Compressor SEC Measured',
                    'UOM',
                    '',
                    'Dryer Type Rated',
                    'Dryer Make And Model Rated',
                    '',
                    'Load time Reading One',
                    'Unload time Reading One',
                    'UOM',
                    'Leakage % One',
                    'UOM',
                    'Load time Reading Two',
                    'Unload time Reading Two',
                    'UOM',
                    'Leakage % Two',
                    'UOM',
                    'Load time Reading Three',
                    'Unload time Reading Three',
                    'UOM',
                    'Leakage % Three',
                    'UOM',
                    '',
                    'VFD or Not',
                    'VFD setting',
                    'Nos. of rewinding of motor',
                    'Check Required pressure',
                    'Check Pressure drop',
                    'Check end use point pressure',
                    'Check inlet air filter DP',
                    'Check load time',
                    'Check unload time',
                    'Load hours',
                    'Run hours',
                    'Ambient Temp.',
                    'Operating Hours',
                    'Observations',
                ];

            case 'chiller':
                return [
                    'Project Name',
                    'Equipment',
                    'Location',
                    'Make & Model',
                    'Year Of Installation',
                    'Type of chiller Rated',
                    'Nos. of Compressor Rated',
                    'Nos. of Compressor Measured',
                    'Capacity Rated',
                    'Capacity Measured',
                    'UOM',
                    'Voltage Rated',
                    'Voltage Measured',
                    'UOM',
                    'Current Rated',
                    'Current Measured',
                    'UOM',
                    'Power Factor Rated',
                    'Power Factor Measured',
                    'Frequency Rated',
                    'Frequency Measured',
                    'UOM',
                    'Speed Rated',
                    'Speed Measured',
                    'UOM',
                    'Motor Power Rated',
                    'Motor Power Measured',
                    'UOM',
                    'Motor Efficiency Rated',
                    'UOM',
                    'Motor Efficiency Class Rated',
                    'Motor Frame Size Rated',
                    'Chiller Loading Measured',
                    'UOM',
                    'Supply Temp. Measured',
                    'UOM',
                    'Return Temp. Measured',
                    'UOM',
                    'Flow Rated',
                    'Flow Measured',
                    'Flow Measured Average',
                    'UOM',
                    'Chiller SEC Rated',
                    'Chiller SEC Measured',
                    'UOM',
                    'Condenser Approach Rated',
                    'Condenser Approach Measured',
                    'UOM',
                    '',
                    'VFD or Not',
                    'VFD setting',
                    'Check set temp. in C',
                    'Check condenser condition',
                    'Take chiller HMI data',
                    'Operating Hours',
                    'Observations',
                ];

            case 'motor':
                return [
                    'Project Name',
                    'Equipment',
                    'Location',
                    'Make & Model',
                    'Year Of Installation',
                    'Voltage Rated',
                    'Voltage Measured',
                    'UOM',
                    'Current Rated',
                    'Current Measured',
                    'UOM',
                    'Power Factor Rated',
                    'Power Factor Measured',
                    'Speed Rated',
                    'Speed Measured',
                    'UOM',
                    'Temp. Measured',
                    'UOM',
                    'Motor Power Rated',
                    'Motor Power Measured',
                    'UOM',
                    'Frequency Rated',
                    'Frequency Measured',
                    'UOM',
                    'Motor Efficiency Rated',
                    'Motor Efficiency Class Rated',
                    'Motor Frame Size Rated',
                    '',
                    'VFD or Not',
                    'VFD setting',
                    'Check per phase current',
                    'Check Phasor',
                    'Nos. of rewinding of motor',
                    'Operating Hours',
                    'Observations',
                ];

            case 'boiler':
                return [
                    'Project Name',
                    'Equipment',
                    'Location',
                    'Make & Model',
                    'Year Of Installation',
                    'Type Of Boiler Rated',
                    'Capacity Rated',
                    'UOM',
                    'Type Of Fuel Rated',
                    'Type Of Fuel Measured',
                    'Type Of Burner Rated',
                    'Average Quantity Of Fuel Fired In A Day Measured',
                    'UOM',
                    '',
                    'Ash Measured',
                    'UOM',
                    'Moisture Measured',
                    'UOM',
                    'Carbon Measured',
                    'UOM',
                    'Hydrogen Measured',
                    'UOM',
                    'Nitrogen Measured',
                    'UOM',
                    'Oxygen Measured',
                    'UOM',
                    'Sulphur Measured',
                    'UOM',
                    'Gross Calorific Value Of Fuel Measured',
                    'UOM',
                    'Net Calorific Value Of Fuel Measured',
                    'UOM',
                    'Flue gas Analysis CO2 Measured',
                    'UOM',
                    'Flue gas Analysis CO Measured',
                    'UOM',
                    'Flue gas Analysis Oxygen Measured',
                    'UOM',
                    'Flue Gas Temperature Measured',
                    'UOM',
                    'Ambient Temperature Measured',
                    'UOM',
                    'Humidity in Air / Kg of Dry Air Measured',
                    'UOM',
                    'Total Surface Area of Boiler Measured',
                    'UOM',
                    'Velocity of Wind Around the Boiler Measured',
                    'UOM',
                    'Average Surface Temperature Measured',
                    'UOM',
                    'Average Quantity of Fuel Fired per hour Measured',
                    'UOM',
                    'GCV of Fly-Ash Measured',
                    'UOM',
                    '% of Fly-Ash / kg of Fuel Measured',
                    'UOM',
                    'GCV of Bottom-Ash Measured',
                    'UOM',
                    'Operating Temp. Rated',
                    'Operating Temp. Measured',
                    'UOM',
                    'Operating Pressure Rated',
                    'Operating Pressure Measured',
                    'UOM',
                    '',
                    'VFD on ID Fan',
                    'VFD setting',
                    'VFD on FD Fan',
                    'VFD setting',
                    'Maximum temp. can sustain',
                    'Alternate fuel possibility',
                    'Blow down control',
                    'Collect Feed water test report',
                    'Blow down water TDS value',
                    'Waste heat recovery',
                    'Burner air max. temp. capacity',
                    'Check steam traps',
                    'Flue gas monitoring',
                    'Online monitoring & control',
                    'Water/steam Flow meter reading',
                    'Fuel Flow meter reading',
                    'Operating Hours',
                    'Observations',


                ];

            case 'cooling':
                return [
                    'Project Name',
                    'Equipment',
                    'Location',
                    'Make & Model',
                    'Year Of Installation',
                    'Capacity Rated',
                    'Capacity Measured',
                    'UOM',
                    'Type of cooling tower Rated',
                    'Entering Water temp. Measured',
                    'UOM',
                    'Leaving Water temp. Measured',
                    'UOM',
                    'Fan Power Rated',
                    'Fan Power Measured',
                    'UOM',
                    'Number of cells Rated',
                    'Number of cells Measured',
                    'Entering air temp. (DBT) Measured',
                    'UOM',
                    'Entering air temp. (WBT) Measured',
                    'UOM',
                    'Leaving air temp. (DBT) Measured',
                    'UOM',
                    'Leaving air temp. (WBT) Measured',
                    'UOM',
                    'Flow of water Measured',
                    'UOM',
                    'Air velocity Measured',
                    'Air velocity Measured Average',
                    'UOM',
                    'Area of fan of CT Measured',
                    'UOM',
                    '',
                    'VFD on fan or not',
                    'VFD setting',
                    'VFD on pump or not',
                    'VFD setting',
                    'Drift loss visible',
                    'Nos. of rewinding of fan motor',
                    'Operating Hours',
                    'Observations',
                ];

            case 'ahu':
                return [
                    'Project Name',
                    'Equipment',
                    'Location',
                    'Make & Model',
                    'Year Of Installation',
                    'Capacity Rated',
                    'Capacity Measured',
                    'UOM',
                    'Type of AHU Rated',
                    'Entering Water temp. Measured',
                    'UOM',
                    'Leaving Water temp. Measured',
                    'UOM',
                    'Fan Power Rated',
                    'Fan Power Measured',
                    'UOM',
                    'Number of cells  Rated',
                    'Number of cells Measured',
                    'Entering air temp. (DBT) Measured',
                    'UOM',
                    'Entering air temp. (WBT) Measured',
                    'UOM',
                    'Leaving air temp. (DBT) Measured',
                    'UOM',
                    'Leaving air temp. (WBT) Measured',
                    'UOM',
                    'Flow of water Measured',
                    'UOM',
                    'Air velocity Measured',
                    'Air velocity Measured Average',
                    'UOM',
                    'Area of duct Measured',
                    'UOM',
                    'Static pressure Rated',
                    'Static pressure Measured',
                    'Static pressure Measured Average',
                    'UOM',
                    'AHU DP Rated',
                    'AHU DP Measured',
                    'AHU DP Measured Average',
                    'UOM',
                    '',
                    'VFD on fan or not',
                    'VFD setting',
                    'Damper position',
                    'Connected with BMS',
                    'Modulating valve is 2 way or 3 way',
                    'Set Temp.',
                    'Operating Hours',
                    'Observations',
                ];

            default:
                return [];
        }
    }

    public function map($equipment): array
    {
        switch ($this->itemType) {
            case 'pump':
                return [
                    $equipment->information->project->name ?? '',
                    'Pump',
                    $equipment->information->name_location ?? '',
                    $equipment->information->make_model ?? '',
                    $equipment->pumpYearOfInstallationRated,
                    $equipment->pumpFlowRated,
                    $equipment->pumpFlowMeasured,
                    $equipment->pumpFlowUnit,
                    $equipment->pumpHeadRated,
                    $equipment->pumpHeadMeasured,
                    'm',
                    $equipment->pumpVoltageRated,
                    $equipment->pumpVoltageMeasured,
                    'V',
                    $equipment->pumpCurrentRated,
                    $equipment->pumpCurrentMeasured,
                    'A',
                    $equipment->pumpPowerFactorRated,
                    $equipment->pumpPowerFactorMeasured,
                    $equipment->pumpMotorPowerRated,
                    $equipment->pumpMotorPowerMeasured,
                    'kW',
                    $equipment->pumpFrequencyRated,
                    $equipment->pumpFrequencyMeasured,
                    'Hz',
                    $equipment->pumpSpeedRated,
                    $equipment->pumpSpeedMeasured,
                    'rpm',
                    $equipment->pumpMotorEfficiencyRated,
                    '%',
                    $equipment->pumpMotorEfficiencyClassRated,
                    $equipment->pumpMotorFrameSizeRated,
                    $equipment->pumpInsulationClassRated,
                    $equipment->pumpSuctionHeadMeasured,
                    'm',
                    $equipment->pumpDischargeHeadMeasured,
                    'm',
                    $equipment->pumpEfficiencyRated,
                    $equipment->pumpEfficiencyMeasured,
                    '',
                    $equipment->pumpVFD,
                    $equipment->pumpVFDsetting,
                    $equipment->pumpThrottling,
                    $equipment->pumpFlowModulationRequired,
                    $equipment->pumpParallelPumpOperation,
                    $equipment->pumpNosOfRewidingOfMotor,
                    $equipment->pumpCheckCavitation,
                    $equipment->pumpOperatingHours,
                    $equipment->information->observations ?? '',
                ];

            case 'fan':
                return [
                    $equipment->information->project->name ?? '',
                    'Fan',
                    $equipment->information->name_location ?? '',
                    $equipment->information->make_model ?? '',
                    $equipment->fanYearOfInstallationRated,
                    $equipment->fanFlowRated,
                    $equipment->fanFlowMeasured,
                    $equipment->fanFlowUnit,
                    $equipment->fanHeadMeasured,
                    'm',
                    $equipment->fanVoltageRated,
                    $equipment->fanVoltageMeasured,
                    'V',
                    $equipment->fanCurrentRated,
                    $equipment->fanCurrentMeasured,
                    'A',
                    $equipment->fanPowerFactorRated,
                    $equipment->fanPowerFactorMeasured,
                    $equipment->fanMotorPowerRated,
                    $equipment->fanMotorPowerMeasured,
                    'kW',
                    $equipment->fanFrequencyRated,
                    $equipment->fanFrequencyMeasured,
                    'Hz',
                    $equipment->fanSpeedRated,
                    $equipment->fanSpeedMeasured,
                    'rpm',
                    $equipment->fanMotorEfficiencyRated,
                    '%',
                    $equipment->fanMotorEfficiencyClassRated,
                    $equipment->fanMotorFrameSizeRated,
                    $equipment->fanInsulationClassRated,
                    $equipment->fanSuctionDuctSizeMeasured,
                    'm2',
                    $equipment->fanSuctionStaticPressureMeasured,
                    $equipment->fanSuctionStaticPressureAverage,
                    $equipment->fanSuctionStaticPressureUnit,
                    $equipment->fanSuctionVelocityPressureMeasured,
                    $equipment->fanSuctionVelocityPressureAverage,
                    $equipment->fanSuctionVelocityPressureUnit,
                    $equipment->fanDischargeDuctSizeMeasured,
                    'm2',
                    $equipment->fanDischargeStaticPressureMeasured,
                    $equipment->fanDischargeStaticPressureAverage,
                    $equipment->fanDischargeStaticPressureUnit,
                    $equipment->fanDischargeVelocityMeasured,
                    $equipment->fanDischargeVelocityAverage,
                    $equipment->fanDischargeVelocityUnit,
                    $equipment->fanDischargeVelocityMeasured,
                    $equipment->fanDischargeVelocityAverage,
                    'm/s',
                    $equipment->fanEfficiencyRated,
                    '',
                    $equipment->fanVFDorNot,
                    $equipment->fanVFDsetting,
                    $equipment->fanOpening,
                    $equipment->fanFlowModulationRequired,
                    $equipment->fanParallelFanOperation,
                    $equipment->fanNosOfRewidingOfMotor,
                    $equipment->fanOperatingHours,
                    $equipment->information->observations ?? '',
                ];

            case 'compressor':
                return [
                    $equipment->information->project->name ?? '',
                    'Air Compressor',
                    $equipment->information->name_location ?? '',
                    $equipment->information->make_model ?? '',
                    $equipment->airCompressorYearOfInstallationRated,
                    $equipment->airCompressorFlowRated,
                    $equipment->airCompressorFlowMeasured,
                    $equipment->airCompressorFlowUnit,
                    $equipment->airCompressorPressureRated,
                    $equipment->airCompressorPressureMeasured,
                    'bar',
                    $equipment->airCompressorVoltageRated,
                    $equipment->airCompressorVoltageMeasured,
                    'V',
                    $equipment->airCompressorCurrentRated,
                    $equipment->airCompressorCurrentMeasured,
                    'A',
                    $equipment->airCompressorPowerFactorRated,
                    $equipment->airCompressorPowerFactorMeasured,
                    $equipment->airCompressorMotorPowerRated,
                    $equipment->airCompressorMotorPowerMeasured,
                    'kW',
                    $equipment->airCompressorFrequencyRated,
                    $equipment->airCompressorFrequencyMeasured,
                    'Hz',
                    $equipment->airCompressorSpeedRated,
                    $equipment->airCompressorSpeedMeasured,
                    'rpm',
                    $equipment->airCompressorMotorEfficiencyRated,
                    '%',
                    $equipment->airCompressorMotorEfficiencyClassRated,
                    $equipment->airCompressorMotorFrameSizeRated,
                    $equipment->airCompressorInsulationClassRated,
                    $equipment->airCompressorLoadPressureMeasured,
                    'bar',
                    $equipment->airCompressorUnLoadPressureMeasured,
                    'bar',
                    $equipment->airCompressorRecieverSizeMeasured,
                    'm3',
                    $equipment->airCompressorPipeVolumeMeasured,
                    'm3',
                    $equipment->airCompressorInitialPressureMeasured,
                    'bar',
                    $equipment->airCompressorFinalPressureMeasured,
                    'bar',
                    $equipment->airCompressorTimeToReachFinalPressureMeasured,
                    'Minutes',
                    $equipment->airCompressorTemperatureMeasured,
                    'C',
                    $equipment->airCompressorCompressorSECRated,
                    $equipment->airCompressorCompressorSECMeasured,
                    'kW/CFM',
                    $equipment->airCompressorDryerTypeRated,
                    $equipment->airCompressorDryerMakeModelRated,
                    '',
                    $equipment->airCompressorLoadTimeReadingOne,
                    $equipment->airCompressorUnLoadTimeReadingOne,
                    'Second',
                    $equipment->airCompressorLeakageReadingOne,
                    '%',
                    $equipment->airCompressorLoadTimeReadingTwo,
                    $equipment->airCompressorUnLoadTimeReadingTwo,
                    'Second',
                    $equipment->airCompressorLeakageReadingTwo,
                    '%',
                    $equipment->airCompressorLoadTimeReadingThree,
                    $equipment->airCompressorUnLoadTimeReadingThree,
                    'Second',
                    $equipment->airCompressorLeakageReadingThree,
                    '%',
                    '',
                    $equipment->airCompressorVFDorNot,
                    $equipment->airCompressorVFDSetting,
                    $equipment->airCompressorNosOfRewidingOfMotor,
                    $equipment->airCompressorCheckRequiredpressure,
                    $equipment->airCompressorCheckPressureDrop,
                    $equipment->airCompressorCheckEndUsePointPressure,
                    $equipment->airCompressorCheckInletAirFilterDp,
                    $equipment->airCompressorCheckLoadTime,
                    $equipment->airCompressorCheckUnLoadTime,
                    $equipment->airCompressorCheckLoadHours,
                    $equipment->airCompressorCheckRunHours,
                    $equipment->airCompressorCheckAmbientTemp,
                    $equipment->airCompressorOperatingHours,
                    $equipment->information->observations ?? ''
                ];
            case 'chiller':
                return [
                    $equipment->information->project->name ?? '',
                    'Chiller',
                    $equipment->information->name_location ?? '',
                    $equipment->information->make_model ?? '',
                    $equipment->chillerYearOfInstallationRated,
                    $equipment->chillerTypeOfChillerRated,
                    $equipment->chillerNosOfCompressorRated,
                    $equipment->chillerNosOfCompressorMeasured,
                    $equipment->chillerCapacityRated,
                    $equipment->chillerCapacityMeasured,
                    $equipment->chillerCapacityUnit,
                    $equipment->chillerVoltageRated,
                    $equipment->chillerVoltageMeasured,
                    'V',
                    $equipment->chillerCurrentRated,
                    $equipment->chillerCurrentMeasured,
                    'A',
                    $equipment->chillerPowerFactorRated,
                    $equipment->chillerPowerFactorMeasured,
                    $equipment->chillerFrequencyRated,
                    $equipment->chillerFrequencyMeasured,
                    'Hz',
                    $equipment->chillerSpeedRated,
                    $equipment->chillerSpeedMeasured,
                    'rpm',
                    $equipment->chillerMotorPowerRated,
                    $equipment->chillerMotorPowerMeasured,
                    'kW',
                    $equipment->chillerMotorEfficiencyRated,
                    '%',
                    $equipment->chillerMotorEfficiencyClassRated,
                    $equipment->chillerMotorFrameSizeRated,
                    $equipment->chillerChillerLoadingMeasured,
                    '%',
                    $equipment->chillerSupplyTempMeasured,
                    'C',
                    $equipment->chillerReturnTempMeasured,
                    'C',
                    $equipment->chillerFlowRated,
                    $equipment->chillerFlowMeasured,
                    $equipment->chillerFlowMeasuredAverage,
                    $equipment->chillerFlowUnit,
                    $equipment->chillerChillerSECRated,
                    $equipment->chillerChillerSECMeasured,
                    'kW/TR',
                    $equipment->chillerCondenserApprochRated,
                    $equipment->chillerCondenserApprochMeasured,
                    'C',
                    '',
                    $equipment->chillerVFDorNot,
                    $equipment->chillerVFDSetting,
                    $equipment->chillerSetTemp,
                    $equipment->chillerCheckCondenserCondition,
                    $equipment->chillerTakeChillerHMIData,
                    $equipment->chillerOperatingHours,
                    $equipment->information->observations ?? ''
                ];

            case 'motor':
                return [
                    $equipment->information->project->name ?? '',
                    'Motor',
                    $equipment->information->name_location ?? '',
                    $equipment->information->make_model ?? '',
                    $equipment->motorYearOfInstallationRated,
                    $equipment->motorVoltageRated,
                    $equipment->motorVoltageMeasured,
                    'V',
                    $equipment->motorCurrentRated,
                    $equipment->motorCurrentMeasured,
                    'A',
                    $equipment->motorPowerFactorRated,
                    $equipment->motorPowerFactorMeasured,
                    $equipment->motorSpeedRated,
                    $equipment->motorSpeedMeasured,
                    'rpm',
                    $equipment->motorTempMeasured,
                    'C',
                    $equipment->motorMotorPowerRated,
                    $equipment->motorMotorPowerMeasured,
                    'KW',
                    $equipment->motorFrequencyRated,
                    $equipment->motorFrequencyMeasured,
                    'Hz',
                    $equipment->motorMotorEfficiencyRated,
                    $equipment->motorMotorEfficiencyClassRated,
                    $equipment->motorMotorFrameSizeRated,
                    '',
                    $equipment->motorVFDorNot,
                    $equipment->motorVFDSetting,
                    $equipment->motorCheckPerPhaseCurrent,
                    $equipment->motorCheckPhasor,
                    $equipment->motorNosOfRewidingOfMotor,
                    $equipment->motorOperatingHours,
                    $equipment->information->observations ?? ''
                ];

            case 'boiler':
                return [
                    $equipment->information->project->name ?? '',
                    'Boiler',
                    $equipment->information->name_location ?? '',
                    $equipment->information->make_model ?? '',
                    $equipment->boilerYearOfInstallationRated,
                    $equipment->boilerTypeOfBoilerRated,
                    $equipment->boilerCapacityRated,
                    $equipment->boilerCapacityUnit,
                    $equipment->boilerTypeOfFuelRated,
                    $equipment->boilerTypeOfFuelMeasured,
                    $equipment->boilerTypeOfBurnerRated,
                    $equipment->boilerAverageQuantityOfFuelFiredInADayMeasured,
                    $equipment->boilerAverageQuantityOfFuelFiredInADayUnit,
                    '',
                    $equipment->boilerAshMeasured,
                    '%',
                    $equipment->boilerMoistureMeasured,
                    '%',
                    $equipment->boilerCarbonMeasured,
                    '%',
                    $equipment->boilerHydrogenMeasured,
                    '%',
                    $equipment->boilerNitrogenMeasured,
                    '%',
                    $equipment->boilerOxygenMeasured,
                    '%',
                    $equipment->boilerSulphurMeasured,
                    '%',
                    $equipment->boilerGrossCalorificValueOfFuelMeasured,
                    $equipment->boilerGrossCalorificValueOfFuelUnit,
                    $equipment->boilerNetCalorificValueOfFuelMeasured,
                    $equipment->boilerNetCalorificValueOfFuelUnit,
                    $equipment->boilerFlueGasAnalysisCO2Measured,
                    '%',
                    $equipment->boilerFlueGasAnalysisCOMeasured,
                    '%',
                    $equipment->boilerFlueGasAnalysisOxygenMeasured,
                    '%',
                    $equipment->boilerFlueGasTemperatureMeasured,
                    'C',
                    $equipment->boilerAmbientTemperatureMeasured,
                    'C',
                    $equipment->boilerHumidityInAirKgOfDryAirMeasured,
                    $equipment->boilerHumidityInAirKgOfDryAirUnit,
                    $equipment->boilerTotalSurfaceAreaOfBoilerMeasured,
                    'm2',
                    $equipment->boilerVelocityOfWindAroundTheBoilerMeasured,
                    'm/s',
                    $equipment->boilerAverageSurfaceTemperatureMeasured,
                    'C',
                    $equipment->boilerAverageQuantityOfFuelFiredPerHourMeasured,
                    $equipment->boilerAverageQuantityOfFuelFiredPerHourUnit,
                    $equipment->boilerGCVOfFlyAshMeasured,
                    $equipment->boilerGCVOfFlyAshUnit,
                    $equipment->boilerFlyAshKgOfFuelMeasured,
                    '%',
                    $equipment->boilerGCVOfBottomAshMeasured,
                    $equipment->boilerGCVOfBottomAshUnit,
                    $equipment->boilerOperatingTempRated,
                    $equipment->boilerOperatingTempMeasured,
                    'C',
                    $equipment->boilerOperatingPressureRated,
                    $equipment->boilerOperatingPressureMeasured,
                    $equipment->boilerOperatingPressureUnit,
                    '',
                    $equipment->boilerVFDOnIdFan,
                    $equipment->boilerVFDOnIdFanVFDSetting,
                    $equipment->boilerVFDOnFdFan,
                    $equipment->boilerVFDOnFdFanVFDSetting,
                    $equipment->boilerMaximumTempCanSustain,
                    $equipment->boilerAlternateFuelPossibility,
                    $equipment->boilerBlowDownControl,
                    $equipment->boilerCollectFeedWaterTestReport,
                    $equipment->boilerBlowDownWaterTDSvalue,
                    $equipment->boilerWasteHeatRecovery,
                    $equipment->boilerBurnerAirMaxTempCapacity,
                    $equipment->boilerCheckSteamTraps,
                    $equipment->boilerFlueGasMonitoring,
                    $equipment->boilerOnlineMonitoringControl,
                    $equipment->boilerWaterSteamFlowMeterReading,
                    $equipment->boilerFuelFlowMeterReading,
                    $equipment->boilerOperatingHours,
                    $equipment->information->observations ?? ''
                ];

            case 'cooling':
                return [
                    $equipment->information->project->name ?? '',
                    'Cooling Tower',
                    $equipment->information->name_location ?? '',
                    $equipment->information->make_model ?? '',
                    $equipment->coolingYearOfInstallationRated,
                    $equipment->coolingCapacityRated,
                    $equipment->coolingCapacityMeasured,
                    $equipment->coolingCapacityUnit,
                    $equipment->coolingTypeOfCoolingTowerRated,
                    $equipment->coolingEnteringWaterTempMeasured,
                    'C',
                    $equipment->coolingLeavingWaterTempMeasured,
                    'C',
                    $equipment->coolingFanPowerRated,
                    $equipment->coolingFanPowerMeasured,
                    'KW',
                    $equipment->coolingNumberOfCellsRated,
                    $equipment->coolingNumberOfCellsMeasured,
                    $equipment->coolingEnteringAirTempDBTMeasured,
                    'C',
                    $equipment->coolingEnteringAirTempWBTMeasured,
                    'C',
                    $equipment->coolingLeavingAirTempDBTMeasured,
                    'C',
                    $equipment->coolingLeavingAirTempWBTMeasured,
                    'C',
                    $equipment->coolingFlowOfWaterMeasured,
                    $equipment->coolingFlowOfWaterUnit,
                    $equipment->coolingAirVelocityMeasured,
                    $equipment->coolingAirVelocityMeasuredAverage,
                    'm/s',
                    $equipment->coolingAreaOfFanOfCTMeasured,
                    'm2',
                    '',
                    $equipment->coolingVFDOnFanOrNot,
                    $equipment->coolingVFDSettingFan,
                    $equipment->coolingVFDOnPumpOrNot,
                    $equipment->coolingVFDSettingPump,
                    $equipment->coolingDriftLossVisible,
                    $equipment->coolingNosOfRewidingOfFanMotor,
                    $equipment->coolingOperatingHours,
                    $equipment->information->observations ?? ''
                ];

            case 'ahu':
                return [
                    $equipment->information->project->name ?? '',
                    'AHU',
                    $equipment->information->name_location ?? '',
                    $equipment->information->make_model ?? '',
                    $equipment->ahuYearOfInstallationRated,
                    $equipment->ahuCapacityRated,
                    $equipment->ahuCapacityMeasured,
                    $equipment->ahuCapacityUnit,
                    $equipment->ahuTypeOfAHURated,
                    $equipment->ahuEnteringWaterTempMeasured,
                    'C',
                    $equipment->ahuLeavingWaterTempMeasured,
                    'C',
                    $equipment->ahuFanPowerRated,
                    $equipment->ahuFanPowerMeasured,
                    'KW',
                    $equipment->ahuNumberOfCellsRated,
                    $equipment->ahuNumberOfCellsMeasured,
                    $equipment->ahuEnteringAirTempDBTMeasured,
                    'C',
                    $equipment->ahuEnteringAirTempWBTMeasured,
                    'C',
                    $equipment->ahuLeavingAirTempDBTMeasured,
                    'C',
                    $equipment->ahuLeavingAirTempWBTMeasured,
                    'C',
                    $equipment->ahuFlowOfWaterMeasured,
                    $equipment->ahuFlowOfWaterUnit,
                    $equipment->ahuAirVelocityMeasured,
                    $equipment->ahuAirVelocityMeasuredAverage,
                    'm/s',
                    $equipment->ahuAirAreaOfDuctMeasured,
                    'm2',
                    $equipment->ahuStaticPressureRated,
                    $equipment->ahuStaticPressureMeasured,
                    $equipment->ahuStaticPressureMeasuredAverage,
                    $equipment->ahuStaticPressureUnit,
                    $equipment->ahuAHUDPRated,
                    $equipment->ahuAHUDPMeasured,
                    $equipment->ahuAHUDPMeasuredAverage,
                    $equipment->ahuAHUDPUnit,
                    '',
                    $equipment->ahuVFDOnFanOrNot,
                    $equipment->ahuVFDSettingFan,
                    $equipment->ahuDamperPosition,
                    $equipment->ahuConnectedWithBMS,
                    $equipment->ahuModulatingValve,
                    $equipment->ahuSetTemp,
                    $equipment->ahuOperatingHours,
                    $equipment->information->observations ?? ''
                ];

            default:
                return [];

        }
    }

    public function styles(Worksheet $sheet)
    {
        return [
            1 => ['font' => ['bold' => true]], // Bold heading row
        ];
    }
}
