<?php

namespace App\Http\Requests;

use Illuminate\Foundation\Http\FormRequest;

class InformationRequest extends FormRequest
{
    /**
     * Determine if the user is authorized to make this request.
     */
    public function authorize(): bool
    {
        return true;
    }

    /**
     * Get the validation rules that apply to the request.
     *
     * @return array<string, \Illuminate\Contracts\Validation\ValidationRule|array<mixed>|string>
     */
    public function rules(): array
    {
        return [
            'itemType' => 'required',
            'images' => 'nullable',
            'observations' => 'nullable|string',

            // Pump
            'pumpYearOfInstallationRated' => 'nullable|string',
            'pumpYearOfInstallationMeasured' => 'nullable|string',
            'pumpFlowRated' => 'nullable|string',
            'pumpFlowMeasured' => 'nullable|string',
            'pumpHeadRated' => 'nullable|string',
            'pumpHeadMeasured' => 'nullable|string',
            'pumpVoltageRated' => 'nullable|string',
            'pumpVoltageMeasured' => 'nullable|string',
            'pumpCurrentRated' => 'nullable|string',
            'pumpCurrentMeasured' => 'nullable|string',
            'pumpPowerFactorRated' => 'nullable|string',
            'pumpPowerFactorMeasured' => 'nullable|string',
            'pumpMotorPowerRated' => 'nullable|string',
            'pumpMotorPowerMeasured' => 'nullable|string',
            'pumpMotorEfficiencyRated' => 'nullable|string',
            'pumpMotorEfficiencyMeasured' => 'nullable|string',
            'pumpMotorEfficiencyClassRated' => 'nullable|string',
            'pumpMotorEfficiencyClassMeasured' => 'nullable|string',
            'pumpMotorFrameSizeRated' => 'nullable|string',
            'pumpMotorFrameSizeMeasured' => 'nullable|string',
            'pumpInsulationClassRated' => 'nullable|string',
            'pumpInsulationClassMeasured' => 'nullable|string',
            'pumpSuctionHeadRated' => 'nullable|string',
            'pumpSuctionHeadMeasured' => 'nullable|string',
            'pumpDischargeHeadRated' => 'nullable|string',
            'pumpDischargeHeadMeasured' => 'nullable|string',
            'pumpEfficiencyRated' => 'nullable|string',
            'pumpEfficiencyMeasured' => 'nullable|string',
            'pumpVFDorNot' => 'nullable|string',
            'pumpVFDSetting' => 'nullable|string',
            'pumpThrottling' => 'nullable|string',
            'pumpFlowModulationRequired' => 'nullable|string',
            'pumpParallelPumpOperation' => 'nullable|string',
            'pumpNosOfRewidingOfMotor' => 'nullable|string',
            'pumpCheckCavitation' => 'nullable|string',
            'pumpOperatingHours' => 'nullable|string',

            // Fan
            'fanYearOfInstallationRated' => 'nullable|string',
            'fanYearOfInstallationMeasured' => 'nullable|string',
            'fanFlowRated' => 'nullable|string',
            'fanFlowMeasured' => 'nullable|string',
            'fanHeadRated' => 'nullable|string',
            'fanHeadMeasured' => 'nullable|string',
            'fanVoltageRated' => 'nullable|string',
            'fanVoltageMeasured' => 'nullable|string',
            'fanCurrentRated' => 'nullable|string',
            'fanCurrentMeasured' => 'nullable|string',
            'fanPowerFactorRated' => 'nullable|string',
            'fanPowerFactorMeasured' => 'nullable|string',
            'fanMotorPowerRated' => 'nullable|string',
            'fanMotorPowerMeasured' => 'nullable|string',
            'fanMotorEfficiencyRated' => 'nullable|string',
            'fanMotorEfficiencyMeasured' => 'nullable|string',
            'fanMotorEfficiencyClassRated' => 'nullable|string',
            'fanMotorEfficiencyClassMeasured' => 'nullable|string',
            'fanMotorFrameSizeRated' => 'nullable|string',
            'fanMotorFrameSizeMeasured' => 'nullable|string',
            'fanInsulationClassRated' => 'nullable|string',
            'fanInsulationClassMeasured' => 'nullable|string',
            'fanSuctionDuctSizeRated' => 'nullable|string',
            'fanSuctionDuctSizeMeasured' => 'nullable|string',
            'fanSuctionStaticPressureRated' => 'nullable|string',
            'fanSuctionStaticPressureMeasured' => 'nullable|string',
            'fanSuctionVelocityPressureRated' => 'nullable|string',
            'fanSuctionVelocityPressureMeasured' => 'nullable|string',
            'fanDischargeDuctSizeRated' => 'nullable|string',
            'fanDischargeDuctSizeMeasured' => 'nullable|string',
            'fanDischargeStaticPressureRated' => 'nullable|string',
            'fanDischargeStaticPressureMeasured' => 'nullable|string',
            'fanDischargeVelocityPressureRated' => 'nullable|string',
            'fanDischargeVelocityPressureMeasured' => 'nullable|string',
            'fanEfficiencyRated' => 'nullable|string',
            'fanEfficiencyMeasured' => 'nullable|string',
            'fanVFDorNot' => 'nullable|string',
            'fanVFDSetting' => 'nullable|string',
            'fanOpening' => 'nullable|string',
            'fanFlowModulationRequired' => 'nullable|string',
            'fanParallelFanOperation' => 'nullable|string',
            'fanNosOfRewidingOfMotor' => 'nullable|string',
            'fanOperatingHours' => 'nullable|string',

            // Air Compressor
            'airCompressorYearOfInstallationRated' => 'nullable|string',
            'airCompressorYearOfInstallationMeasured' => 'nullable|string',
            'airCompressorFlowRated' => 'nullable|string',
            'airCompressorFlowMeasured' => 'nullable|string',
            'airCompressorPressureRated' => 'nullable|string',
            'airCompressorPressureMeasured' => 'nullable|string',
            'airCompressorVoltageRated' => 'nullable|string',
            'airCompressorVoltageMeasured' => 'nullable|string',
            'airCompressorCurrentRated' => 'nullable|string',
            'airCompressorCurrentMeasured' => 'nullable|string',
            'airCompressorPowerFactorRated' => 'nullable|string',
            'airCompressorPowerFactorMeasured' => 'nullable|string',
            'airCompressorMotorPowerRated' => 'nullable|string',
            'airCompressorMotorPowerMeasured' => 'nullable|string',
            'airCompressorMotorEfficiencyRated' => 'nullable|string',
            'airCompressorMotorEfficiencyMeasured' => 'nullable|string',
            'airCompressorMotorEfficiencyClassRated' => 'nullable|string',
            'airCompressorMotorEfficiencyClassMeasured' => 'nullable|string',
            'airCompressorMotorFrameSizeRated' => 'nullable|string',
            'airCompressorMotorFrameSizeMeasured' => 'nullable|string',
            'airCompressorInsulationClassRated' => 'nullable|string',
            'airCompressorInsulationClassMeasured' => 'nullable|string',
            'airCompressorLoadPressureRated' => 'nullable|string',
            'airCompressorLoadPressureMeasured' => 'nullable|string',
            'airCompressorUnLoadPressureRated' => 'nullable|string',
            'airCompressorUnLoadPressureMeasured' => 'nullable|string',
            'airCompressorRecieverSizeRated' => 'nullable|string',
            'airCompressorRecieverSizeMeasured' => 'nullable|string',
            'airCompressorInitialPressureRated' => 'nullable|string',
            'airCompressorInitialPressureMeasured' => 'nullable|string',
            'airCompressorFinalPressureRated' => 'nullable|string',
            'airCompressorFinalPressureMeasured' => 'nullable|string',
            'airCompressorTimeToReachFinalPressureRated' => 'nullable|string',
            'airCompressorTimeToReachFinalPressureMeasured' => 'nullable|string',
            'airCompressorTemperatureRated' => 'nullable|string',
            'airCompressorTemperatureMeasured' => 'nullable|string',
            'airCompressorCompressorSECRated' => 'nullable|string',
            'airCompressorCompressorSECMeasured' => 'nullable|string',
            'airCompressorLoadTimeReadingOne' => 'nullable|string',
            'airCompressorLoadTimeReadingTwo' => 'nullable|string',
            'airCompressorUnLoadTimeReadingOne' => 'nullable|string',
            'airCompressorUnLoadTimeReadingTwo' => 'nullable|string',
            'airCompressorVFDorNot' => 'nullable|string',
            'airCompressorNosOfRewidingOfMotor' => 'nullable|string',
            'airCompressorCheckRequiredpressure' => 'nullable|string',
            'airCompressorCheckPressureDrop' => 'nullable|string',
            'airCompressorOperatingHours' => 'nullable|string',

            // Chiller
            'chillerYearOfInstallationRated' => 'nullable|string',
            'chillerYearOfInstallationMeasured' => 'nullable|string',
            'chillerCapacityRated' => 'nullable|string',
            'chillerCapacityMeasured' => 'nullable|string',
            'chillerVoltageRated' => 'nullable|string',
            'chillerVoltageMeasured' => 'nullable|string',
            'chillerCurrentRated' => 'nullable|string',
            'chillerCurrentMeasured' => 'nullable|string',
            'chillerPowerFactorRated' => 'nullable|string',
            'chillerPowerFactorMeasured' => 'nullable|string',
            'chillerMotorPowerRated' => 'nullable|string',
            'chillerMotorPowerMeasured' => 'nullable|string',
            'chillerMotorEfficiencyRated' => 'nullable|string',
            'chillerMotorEfficiencyMeasured' => 'nullable|string',
            'chillerMotorEfficiencyClassRated' => 'nullable|string',
            'chillerMotorEfficiencyClassMeasured' => 'nullable|string',
            'chillerMotorFrameSizeRated' => 'nullable|string',
            'chillerMotorFrameSizeMeasured' => 'nullable|string',
            'chillerSupplyTempRated' => 'nullable|string',
            'chillerSupplyTempMeasured' => 'nullable|string',
            'chillerReturnTempRated' => 'nullable|string',
            'chillerReturnTempMeasured' => 'nullable|string',
            'chillerFlowRated' => 'nullable|string',
            'chillerFlowMeasured' => 'nullable|string',
            'chillerChillerSECRated' => 'nullable|string',
            'chillerChillerSECMeasured' => 'nullable|string',
            'chillerCondenserApprochRated' => 'nullable|string',
            'chillerCondenserApprochMeasured' => 'nullable|string',
            'chillerVFDorNot' => 'nullable|string',
            'chillerSetTemp' => 'nullable|string',
            'chillerCheckCondenserCondition' => 'nullable|string',
            'chillerOperatingHours' => 'nullable|string',

            // Motor
            'motorYearOfInstallationRated' => 'nullable|string',
            'motorYearOfInstallationMeasured' => 'nullable|string',
            'motorNameOfEquipmentRated' => 'nullable|string',
            'motorNameOfEquipmentMeasured' => 'nullable|string',
            'motorVoltageRated' => 'nullable|string',
            'motorVoltageMeasured' => 'nullable|string',
            'motorCurrentRated' => 'nullable|string',
            'motorCurrentMeasured' => 'nullable|string',
            'motorPowerFactorRated' => 'nullable|string',
            'motorPowerFactorMeasured' => 'nullable|string',
            'motorMotorPowerRated' => 'nullable|string',
            'motorMotorPowerMeasured' => 'nullable|string',
            'motorMotorEfficiencyRated' => 'nullable|string',
            'motorMotorEfficiencyMeasured' => 'nullable|string',
            'motorMotorEfficiencyClassRated' => 'nullable|string',
            'motorMotorEfficiencyClassMeasured' => 'nullable|string',
            'motorMotorFrameSizeRated' => 'nullable|string',
            'motorMotorFrameSizeMeasured' => 'nullable|string',
            'motorVFDorNot' => 'nullable|string',
            'motorCheckPerPhaseCurrent' => 'nullable|string',
            'motorCheckPhasor' => 'nullable|string',
            'motorNosOfRewidingOfMotor' => 'nullable|string',
            'motorOperatingHours' => 'nullable|string',
        ];
    }
}
